### ISSUE TITLE
get_artist | Undefined property: stdClass::$musicImmersiveHeaderRenderer

### ISSUE THREAD

**Issue by JibayMcs** [theyak/ytmusicapi-php#1]
Hi !

Thank you so much for you work ! It's an amazing wrapper !

But I'm encountering an issue, using it in Laravel v10.

### Usage

```php
dd($this->youtube->getYTMusicAPI()->get_artist('UCK3inMNRNAVUleEbpDU1k2g'));
```
### Issue

![image](https://github.com/theyak/ytmusicapi-php/assets/7621593/26cbae7a-c054-4c6e-b845-34bad5bbfab4)

Tell me if you need more informations.

Thanks for you help !

Best regards

**Comment by theyak** [comment]
Thanks for your report! I've verified this issue also occurs in the original Python version of the library. It looks like YouTube Music considers this to be a regular YouTube user rather than an artist, so it isn't returning the standard artist information. I've made some updates in v0.1.4 which should fix this issue. I'll leave this open until you can verify it is working.

**Comment by JibayMcs** [comment]
Allright !

Now it works like a charm !

Before your fix, i've partially fixed with a try/catch....

Thanks for your reactivity ! You saved my week-end ! :D
